language: ruby
cache: bundler

rvm:
 - 1.9.3

script: 'bundle exec rake'

notifications:
    email:
        recipients:
            - patrick.reames@gmail.com
        on_failure: change
        on_sucess: never